=== joergbirkhold/test1/publicationdata/xml/Magazine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >

    <xsd:complexType name="contentype">
    	<xsd:sequence>
    		<xsd:element ref="modules"></xsd:element>
    	</xsd:sequence>
        <xsd:attributeGroup ref="contentattributes"></xsd:attributeGroup>
    </xsd:complexType>

    <xsd:complexType name="imagetype">
    	<xsd:complexContent>
    		<xsd:extension base="visiblemediatype"></xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="slideshowtype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:sequence>
    				<xsd:element ref="content" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    			</xsd:sequence>
    			<xsd:attributeGroup ref="rsmattributes"></xsd:attributeGroup>
                <xsd:attributeGroup ref="slideshowgroup"></xsd:attributeGroup>
            </xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="linkagetype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:sequence>
    				<xsd:element ref="link" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    			</xsd:sequence>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="videotype">
    	<xsd:complexContent>
    		<xsd:extension base="visiblemediatype"><xsd:attributeGroup ref="videoattributes"></xsd:attributeGroup></xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="audiotype">
    	
        <xsd:attributeGroup ref="audioattributes"></xsd:attributeGroup>
    </xsd:complexType>

    <xsd:complexType name="taboverlaytype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:sequence>
    				<xsd:element ref="content" minOccurs="1" maxOccurs="1"></xsd:element>
    			</xsd:sequence>
    			<xsd:attributeGroup ref="tabgroup"></xsd:attributeGroup>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="imagepopuptype"></xsd:complexType>

    <xsd:complexType name="modulestype">
        <xsd:sequence>

        	<xsd:element ref="audio" minOccurs="0"
        		maxOccurs="unbounded">
        	</xsd:element>
        	<xsd:element ref="image" minOccurs="0"
        		maxOccurs="unbounded">
        	</xsd:element>
        	<xsd:element ref="imagepopup" minOccurs="0"
        		maxOccurs="unbounded">
        	</xsd:element>
        	<xsd:element ref="linkage" minOccurs="0"
        		maxOccurs="unbounded">
        	</xsd:element>
        	<xsd:element ref="slideshow" minOccurs="0"
        		maxOccurs="unbounded">
        	</xsd:element>
        	<xsd:element ref="taboverlay" minOccurs="0"
        		maxOccurs="unbounded">
        	</xsd:element>
        	<xsd:element ref="video" minOccurs="0"
        		maxOccurs="unbounded">
        	</xsd:element>
        	<!--         	<xsd:element ref="taboverlay" minOccurs="0" -->
        	<!--         		maxOccurs="unbounded"> -->
        	<!--         	</xsd:element> -->
        	<xsd:element ref="ar" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        	<xsd:element ref="panorama" minOccurs="0" maxOccurs="1"></xsd:element>
        	<xsd:element ref="hotspots" minOccurs="0" maxOccurs="1"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="video" type="videotype"></xsd:element>
    
    <xsd:element name="linkage" type="linkagetype"></xsd:element>

    <xsd:element name="image" type="imagetype"></xsd:element>

    <xsd:element name="slideshow" type="slideshowtype"></xsd:element>

    <xsd:element name="content" type="contentype"></xsd:element>

    <xsd:element name="taboverlay" type="taboverlaytype"></xsd:element>

    <xsd:element name="imagepopup" type="imagepopuptype"></xsd:element>

    <xsd:element name="audio" type="audiotype"></xsd:element>

    <xsd:element name="modules" type="modulestype"></xsd:element>

    <xsd:attributeGroup name="audioattributes">
    	<xsd:attribute name="source" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="autoplay" type="xsd:boolean"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="loop" type="xsd:boolean" use="required"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="imageattributes">
    	<xsd:attribute name="source" type="xsd:string"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:complexType name="visiblemediatype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:attributeGroup ref="visiblemediaAttributes"></xsd:attributeGroup>
    			<xsd:attributeGroup ref="rsmattributes"></xsd:attributeGroup>
            </xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>
    
    <xsd:attributeGroup name="rectboundedattributes">
    	<xsd:attribute name="x" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="y" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="width" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="height" type="xsd:int" use="required"></xsd:attribute>
         <xsd:attribute name="moduleid" type="xsd:string"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:complexType name="rectboundedtype">
    	<xsd:attributeGroup ref="rectboundedattributes"></xsd:attributeGroup></xsd:complexType>

    <xsd:attributeGroup name="visiblemediaAttributes">
    	<xsd:attribute name="source" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="interactionenabled" type="xsd:boolean"></xsd:attribute>
       
    </xsd:attributeGroup>

    <xsd:complexType name="linktype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:attributeGroup ref="linkattributes"></xsd:attributeGroup>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>
    
    <xsd:attributeGroup name="linkattributes">
    	<xsd:attribute name="linktype" use="required">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:enumeration value="page"></xsd:enumeration>
    				<xsd:enumeration value="slide"></xsd:enumeration>
    				<xsd:enumeration value="contactoverlay"></xsd:enumeration>
    				<xsd:enumeration value="fsvideo"></xsd:enumeration>
    				<xsd:enumeration value="section"></xsd:enumeration>
    				<xsd:enumeration value="infooverlay"></xsd:enumeration>
    				<xsd:enumeration value="emailattachment"></xsd:enumeration>
    				<xsd:enumeration value="url"></xsd:enumeration>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    	<xsd:attribute name="pagenumber" type="xsd:int"
    		use="optional">
    	</xsd:attribute>
    	<xsd:attribute name="slidenumber" type="xsd:int"
    		use="optional">
    	</xsd:attribute>
    	<xsd:attribute name="videosource" type="xsd:string"
    		use="optional">
    	</xsd:attribute>
    	<!--         <xsd:attribute name="moduleid" type="xsd:string" use="optional"></xsd:attribute> -->
    	<xsd:attribute name="emailsubject" type="xsd:string"
    		use="optional">
    	</xsd:attribute>
    	<xsd:attribute name="emailbody" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="emailattachment" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="url" type="xsd:anyURI"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="rsmattributes">
    	<xsd:attribute name="allowrotation" type="xsd:boolean" use="required"></xsd:attribute>
    	<xsd:attribute name="allowmovement" type="xsd:boolean" use="required"></xsd:attribute>
    	<xsd:attribute name="allowzoom" type="xsd:boolean" use="required"></xsd:attribute>
    	<xsd:attribute name="doubletaptoFS" type="xsd:boolean" use="required"></xsd:attribute>
    	<xsd:attribute name="pinchtoFS" type="xsd:boolean" use="required"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:element name="link" type="linktype"></xsd:element>

    <xsd:element name="page" type="pagetype"></xsd:element>

    <xsd:complexType name="pagetype">
    	<xsd:sequence>
    		<xsd:element ref="content" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
        <xsd:attributeGroup ref="pageattributegroup"></xsd:attributeGroup>
    </xsd:complexType>

    <xsd:element name="publication" type="publicationtype"></xsd:element>

    <xsd:complexType name="publicationtype">
    	<xsd:sequence>
    		<xsd:element ref="page" minOccurs="0"
    			maxOccurs="unbounded">
    		</xsd:element>
    		<xsd:element ref="chapter" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
        <xsd:attributeGroup ref="publicationgroup"></xsd:attributeGroup>
    </xsd:complexType>

    <xsd:attributeGroup name="videoattributes">
    	<xsd:attribute name="loop" type="xsd:boolean" use="required"></xsd:attribute>
    	<xsd:attribute name="autoplay" type="xsd:boolean"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="showcontrols" type="xsd:boolean"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="hideonend" type="xsd:boolean"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="firstframe" type="xsd:string"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="fsrectgroup">
    	<xsd:attribute name="fsx" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="fsy" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="fswidth" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="fsheight" type="xsd:int" use="required"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="slideshowgroup">
    	<xsd:attribute name="ispaging" type="xsd:boolean" use="required" ></xsd:attribute>
    	<xsd:attribute name="hassubtitles" type="xsd:boolean" use="optional" default="false"></xsd:attribute> 
    	<xsd:attribute name="subtitlex" type="xsd:int" use="optional"></xsd:attribute>
    	<xsd:attribute name="subtitley" type="xsd:int" use="optional"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="tabgroup">
    	<xsd:attribute name="tabx" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="taby" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="tabwidth" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="tabheight" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="buttonx" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="buttony" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="buttonwidth" type="xsd:int"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="buttonheight" type="xsd:int"
    		use="required">
    	</xsd:attribute>
    	<xsd:attribute name="bgcolor" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="bgalpha" type="xsd:string"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="pageattributegroup">
    	<xsd:attribute name="number" type="xsd:int" use="optional"></xsd:attribute>
    	<xsd:attribute name="section" type="xsd:string" use="optional"></xsd:attribute>
    	<xsd:attribute name="bgcolor" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:complexType name="artype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype"></xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="ar" type="artype"></xsd:element>

    <xsd:attributeGroup name="contentattributes">
    	<xsd:attribute name="subtitle" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:complexType name="panoramatype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:sequence>
    				<xsd:element ref="hotspots"></xsd:element>
    			</xsd:sequence>
    			<xsd:attributeGroup ref="panoramagroup"></xsd:attributeGroup>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:attributeGroup name="panoramagroup">
    	<xsd:attribute name="tilefolder" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="imagename" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="imagewidth" type="xsd:int" use="required"></xsd:attribute>
    	<xsd:attribute name="imageheight" type="xsd:int" use="required"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:element name="panorama" type="panoramatype"></xsd:element>

    <xsd:complexType name="chaptertype">
    	<xsd:sequence>
    		<xsd:element ref="page" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    	</xsd:sequence>
        <xsd:attributeGroup ref="chaptergroup"></xsd:attributeGroup>
    </xsd:complexType>

    <xsd:element name="chapter" type="chaptertype"></xsd:element>

    <xsd:attributeGroup name="chaptergroup">
    	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="number" type="xsd:int"></xsd:attribute>
    </xsd:attributeGroup>

    <xsd:attributeGroup name="publicationgroup">
    	<xsd:attribute name="orientation" use="required">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:enumeration value="landscape"></xsd:enumeration>
    				<xsd:enumeration value="portrait"></xsd:enumeration>
    				<xsd:enumeration value="any"></xsd:enumeration>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    	<xsd:attribute name="navigationtype" use="required">
    		<xsd:simpleType>
    			<xsd:restriction base="xsd:string">
    				<xsd:enumeration value="flip"></xsd:enumeration>
    				<xsd:enumeration value="swipe"></xsd:enumeration>
    			</xsd:restriction>
    		</xsd:simpleType>
    	</xsd:attribute>
    </xsd:attributeGroup>

    <xsd:complexType name="hotspottype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:sequence>
    				<xsd:element name="smallview" type="hotspotsmallviewtype" minOccurs="0" maxOccurs="1"></xsd:element>
    				<xsd:element name="fullscreenview" type="hotspotfullscreentype" minOccurs="0" maxOccurs="1"></xsd:element>
    			</xsd:sequence>
    			<xsd:attributeGroup ref="hotspotattributes"></xsd:attributeGroup>
            </xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="hotspotstype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:sequence>
    				<xsd:element ref="hotspot" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    			</xsd:sequence>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="hotspots" type="hotspotstype"></xsd:element>

    <xsd:element name="hotspot" type="hotspottype"></xsd:element>

    <xsd:attributeGroup name="hotspotattributes">
    	<xsd:attribute name="imgsource" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="enabled" type="xsd:boolean"></xsd:attribute>
    </xsd:attributeGroup>
    
    <xsd:complexType name="hotspotsmallviewtype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:sequence>
    				<xsd:element ref="content"></xsd:element>
    			</xsd:sequence>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="hotspotfullscreentype">
    	<xsd:complexContent>
    		<xsd:extension base="rectboundedtype">
    			<xsd:sequence>
    				<xsd:element ref="content"></xsd:element>
    			</xsd:sequence>
    		</xsd:extension>
    	</xsd:complexContent>
    </xsd:complexType>
</xsd:schema>

=== joergbirkhold/test1/publicationdata/xml/region_hannover_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<publication navigationtype="flip" orientation="portrait"
             xsi:noNamespaceSchemaLocation="Magazine.xsd"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <!--ERSTEN SEITEN -->
    <chapter name="chapter_00" number="00">
        
        
        <page bgcolor="#FFFFFF" number="0">
            <content>
                <modules>
                    <image allowmovement="false" allowrotation="false" allowzoom="false" doubletaptoFS="false" height="1024" pinchtoFS="false" source="publicationdata/pages/chapter_00/Erklaerungsseite.jpg"
                        width="768" x="0" y="0" />
                </modules>
            </content>
        </page>
        
        
        <page bgcolor="#FFFFFF" number="1">
            <content>
                <modules>
                    <image allowmovement="false" allowrotation="false" allowzoom="false"
                    doubletaptoFS="false" height="1024" pinchtoFS="false"
                    source="publicationdata/pages/chapter_00/Logistikumschlag_APP_1.jpg"
                    width="768" x="0" y="0"/>
                </modules>
            </content>
        </page>
        
        <page bgcolor="#FFFFFF" number="2">
            <content>
                <modules>
                    <image allowmovement="false" allowrotation="false" allowzoom="false"
                    doubletaptoFS="false" height="1024" pinchtoFS="false"
                    source="publicationdata/pages/chapter_00/Logistikumschlag_APP_2.jpg"
                    width="768" x="0" y="0"/>
                </modules>
            </content>
        </page>
        
        <page bgcolor="#FFFFFF" number="3">
            <content>
                <modules>
                    <image allowmovement="false" allowrotation="false" allowzoom="false"
                    doubletaptoFS="false" height="1024" pinchtoFS="false"
                    source="publicationdata/pages/chapter_00/Logistikumschlag_APP_3.jpg"
                    width="768" x="0" y="0"/>
                </modules>
            </content>
        </page>
        
        <page bgcolor="#FFFFFF" number="4">
            <content>
                <modules>
                    <image allowmovement="false" allowrotation="false" allowzoom="false"
                    doubletaptoFS="false" height="1024" pinchtoFS="false"
                    source="publicationdata/pages/chapter_00/Logistikumschlag_APP_4.jpg"
                    width="768" x="0" y="0"/>
                </modules>
            </content>
        </page>
    </chapter>
    <!--ERSTEN SEITEN -->
    
  <chapter name="chapter_01" number="1">
    <page bgcolor="#FFFFFF" number="5">
      <content>
        <modules>
          <image allowmovement="false" allowrotation="false" allowzoom="false"
                 doubletaptoFS="false" height="1024" pinchtoFS="false"
                 source="publicationdata/pages/chapter_01/Logistik_Page_001.jpg"
                 width="768" x="0" y="0"/>
            
            <linkage height="1024" width="768" x="0" y="0">
                <!--Chapter-->
                <link height="48" width="48" x="647" y="258" linktype="page"
                pagenumber="6" /> <!-- Zusammenfassung -->
                <link height="48" width="48" x="647" y="320" linktype="page"
                pagenumber="8" /> <!-- Chapter 1 -->
                <link height="48" width="48" x="647" y="382" linktype="page"
                pagenumber="10" /> <!-- Chapter 2 -->
                <link height="48" width="48" x="647" y="537" linktype="page"
                pagenumber="36" /> <!-- Chapter 3 -->
                <link height="48" width="48" x="647" y="693" linktype="page"
                pagenumber="44" /> <!-- Chapter 4 -->
                <link height="48" width="48" x="647" y="816" linktype="page"
                pagenumber="55" /> <!-- Chapter 5 -->
                <link height="48" width="48" x="647" y="878" linktype="page"
                pagenumber="57" /> <!-- Impressum -->
                <!--Chapter-->
                
                <!--Seiten-->
                
                <link height="25" width="85" x="516" y="255" linktype="page"
                pagenumber="6" />
                <link height="29" width="157" x="70" y="255" linktype="page"
                pagenumber="6" /><!-- 2 -->
                
                <link height="25" width="85" x="516" y="319" linktype="page"
                pagenumber="8" />
                <link height="30" width="214" x="70" y="311" linktype="page"
                pagenumber="8" /><!-- 4 -->
                
                <link height="25" width="85" x="516" y="379" linktype="page"
                pagenumber="10" />
                <link height="29" width="214" x="70" y="375" linktype="page"
                pagenumber="10" /><!-- 6 -->
                
                <link height="25" width="85" x="516" y="411" linktype="page"
                pagenumber="17" />
                <link height="23" width="307" x="70" y="413" linktype="page"
                pagenumber="17" /><!-- 13 -->
                
                <link height="25" width="85" x="516" y="442" linktype="page"
                pagenumber="26" />
                <link height="22" width="326" x="70" y="445" linktype="page"
                pagenumber="26" /><!-- 22 -->
                
                <link height="25" width="85" x="516" y="473" linktype="page"
                pagenumber="30" />
                <link height="19" width="234" x="70" y="476" linktype="page"
                pagenumber="30" /><!-- 26 -->
                
                <link height="25" width="85" x="516" y="535" linktype="page"
                pagenumber="36" />
                <link height="22" width="331" x="70" y="537" linktype="page"
                pagenumber="36" /><!-- 32 -->
                
                <link height="25" width="85" x="516" y="565" linktype="page"
                pagenumber="37" />
                <link height="25" width="382" x="70" y="566" linktype="page"
                pagenumber="37" /><!-- 33 -->
                
                <link height="25" width="85" x="516" y="598" linktype="page"
                pagenumber="41" />
                <link height="24" width="243" x="70" y="600" linktype="page"
                pagenumber="41" /><!-- 37 -->
                
                <link height="25" width="85" x="516" y="628" linktype="page"
                pagenumber="43" />
                <link height="20" width="187" x="70" y="632" linktype="page"
                pagenumber="43" /><!-- 39 -->
                
                <link height="25" width="85" x="516" y="690" linktype="page"
                pagenumber="44" />
                <link height="25" width="390" x="70" y="690" linktype="page"
                pagenumber="44" /><!-- 40 -->
                
                <link height="25" width="85" x="516" y="722" linktype="page"
                pagenumber="47" />
                <link height="26" width="366" x="70" y="721" linktype="page"
                pagenumber="47" /><!-- 43 -->
                
                <link height="25" width="85" x="516" y="752" linktype="page"
                pagenumber="52" />
                <link height="24" width="289" x="70" y="754" linktype="page"
                pagenumber="52" /><!-- 48 -->
                
                <link height="25" width="85" x="516" y="815" linktype="page"
                pagenumber="55" />
                <link height="22" width="114" x="70" y="817" linktype="page"
                pagenumber="55" /><!-- 51 -->
                
                <link height="25" width="85" x="516" y="877" linktype="page"
                pagenumber="57" />
                <link height="24" width="101" x="70" y="878" linktype="page"
                pagenumber="57" /><!-- 53 -->
            </linkage>
            <!-- Seiten -->
            
        </modules>
      </content>
    </page>

    <page bgcolor="#FFFFFF" number="6">
      <content>
        <modules>
          <image allowmovement="false" allowrotation="false" allowzoom="false"
                 doubletaptoFS="false" height="1024" pinchtoFS="false"
                 source="publicationdata/pages/chapter_01/Logistik_Page_002.jpg"
                 width="768" x="0" y="0"/>
        </modules>
      </content>
    </page>

    <page bgcolor="#FFFFFF" number="7">
      <content>
        <modules>
          <image allowmovement="false" allowrotation="false" allowzoom="false"
                 doubletaptoFS="false" height="1024" pinchtoFS="false"
                 source="publicationdata/pages/chapter_01/Logistik_Page_003.jpg"
                 width="768" x="0" y="0"/>
        </modules>
      </content>
    </page>

    <page bgcolor="#FFFFFF" number="8">
      <content>
        <modules>
          <image allowmovement="false" allowrotation="false" allowzoom="false"
                 doubletaptoFS="false" height="1024" pinchtoFS="false"
                 source="publicationdata/pages/chapter_01/Logistik_Page_004.jpg"
                 width="768" x="0" y="0"/>
            
            <slideshow allowmovement="true" allowrotation="true"
                allowzoom="true" doubletaptoFS="true" height="233"
                ispaging="true" pinchtoFS="true" width="412" x="286"
                y="739">
                <content>
                    <modules>
                        <image allowmovement="false" allowrotation="false"
                        allowzoom="false" doubletaptoFS="false" height="233"
                        pinchtoFS="false"
                        source="publicationdata/pages/chapter_01/slideshow_04/Logistik_Page_004_Abb_1_1.jpg"
                        width="412" x="0" y="0"/>
                    </modules>
                </content>
                <content>
                    <modules>
